### ISSUE TITLE
引用循环

### ISSUE THREAD

**Issue by ApolloZhu** [LiulietLee/BilibiliCD#20]
objcio 这期是 private 有点可惜，不过可以阅读  https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/AutomaticReferenceCounting.html

总结一下，需要这样修改
```diff
--- protocol <#XXX#>Delegate        {
+++ protocol <#XXX#>Delegate: AnyObject {
```
```diff
---      var delegate: <#XXX#>Delegate
+++ weak var delegate: <#XXX#>Delegate?
```

**Comment by LiulietLee** [comment]
诶嘿嘿
