### ISSUE TITLE
[UI] 更便捷的搜索按钮 + [TODO] 功能建议

### ISSUE THREAD

**Issue by ApolloZhu** [LiulietLee/BilibiliCD#4]
# 界面设计

<details>
<summary>目前搜索按钮在屏幕的左上角，不是很方便，建议移到右下角</summary>
Currently, search button is located at the upper left corner, which makes it REALLY hard to reach. Thus I purpose making it to the lower right corner might be better.
</details>

![image](https://user-images.githubusercontent.com/10842684/29999621-c556d46e-901d-11e7-82f0-b03a30bfc556.png)

# 功能建议
<details>
<summary>支持桌面 3D Touch 快速打开剪贴板里的链接（文字仅供参考）</summary>
Support open pasteboard URL using Home Screen Quick Action (3D Touch) 
These are just a few possibilities, I strongly recommend using better phrasing for this.
</details>

![image](https://user-images.githubusercontent.com/10842684/29999837-0b599468-9025-11e7-80eb-fd99279f4012.png)

<details>
<summary>在识别到剪贴板中是 `d+` 而不是标准 av`d+` 格式的时候，询问是否打开</summary>
Show snack bar when detect url in pasteboard instead of just going the page.
</details>

<img src="https://user-images.githubusercontent.com/10842684/29999870-ade39918-9025-11e7-9f6b-084e58190c3e.png" width=350 />

**Comment by LiulietLee** [comment]
这个 App 基本上只有国人会用所以 Issue 就用中文交流吧。

把搜索按钮放到下面我是考虑过的，没这么搞是因为这样会破坏界面整体的对称性，另外这个页面在真正使用过程中基本不会用到，因为 App 本身侧重点在通过复制链接的方式获取封面而不是自己敲av号。

关于 3D Touch 我没做是因为家里穷买不起有 3D Touch 的设备 = = 等啥时候我有设备了再开发这些东西吧。

**Comment by ApolloZhu** [comment]
上面改成中文了

我也考虑过对称性，不过总感觉把删除键放下面有些怪

<img src="https://user-images.githubusercontent.com/10842684/30003469-435d14a0-908b-11e7-80e4-c6ad3ce3e287.png" height=300>

3D touch 我也没有... 只是觉得有比没有好。不知道 Extension 支不支持保存图片, 可以的话 Today Widget 其实是最好的选项（类似 Pin 或者 方片收集）

**Comment by LiulietLee** [comment]
所以主页面我暂时就先不改了，Today Widget 这东西等我军训完了研究一下。
