### ISSUE TITLE
[BUG] Incorrectly displays the close button in the tutorial

### ISSUE THREAD

**Issue by uetcis** [LiulietLee/BilibiliCD#6]
![simulator screen shot - iphone x - 2017-09-23 at 20 48 48](https://user-images.githubusercontent.com/25654046/30773313-090520b0-a0a1-11e7-9329-c81237ccc5d2.png)

**Comment by uetcis** [comment]
[Advice]
Maybe you'd better try the Onboard framework
You can make excellent tutorials with that easily

**Comment by LiulietLee** [comment]
我已经发现这个问题了，不过暂时不打算管它，因为……我懒得去适配 iPhone X

**Comment by ApolloZhu** [comment]
bringSubview(toFront) 如何，按钮具体设计美化（比如后面加个白色圆形背景之类的）的处理就交给你们了


![image](https://user-images.githubusercontent.com/10842684/30776952-f86b481a-a07d-11e7-9624-2e47f55ffd19.png)

**Comment by uetcis** [comment]
其实我觉得上面空那么大一块不符合Guidelines吧
而且下面的PageControl控件应该放在SafeArea吧

**Comment by ApolloZhu** [comment]
上面那块空着是因为图片不够大...
下面这个 page control 应该是系统自带的行为，没动过
有没有什么建议？

**Comment by uetcis** [comment]
我先去重温一下iPhoneX的Design视频。。。

**Comment by LiulietLee** [comment]
直接单独为 iPhone X 写一套约束怎么样？

**Comment by uetcis** [comment]
我觉得OK

**Comment by LiulietLee** [comment]
暂时保持现在这个样子吧，iPhone X 这个奇葩我已经不想管了
